- hosts: dev
  gather_facts: no
  tasks:
  - win_chocolatey:
      name: chocolatey
      state: present  
  - win_chocolatey:
      name: procexp
      state: present
  - win_chocolatey:
      name: notepadplusplus
      state: present    
  - win_chocolatey:
      name: visualstudio2017enterprise
      state: present    
    